<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorMessage</name>
   <tag></tag>
   <elementGuidId>beabd9ef-1ca6-4f36-a6c7-448474f518a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#katalon-rec_elementInfoDiv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7cab65dd-dc2e-43a3-a7f3-3fc385a19397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
      <webElementGuid>00571e0f-7eee-413e-a2a2-aa728e7ac9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/table[2]/tbody[1]/tr[1]/td[1]/fieldset[1]/table[1]/tbody[1]/tr[5]/td[1]/div[1]/ul[@class=&quot;errorMessage&quot;]/li[1]/span[1]</value>
      <webElementGuid>d6324183-73d5-49c4-ad6e-2ebbf74b33df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>f97853ea-f2c5-4595-8c3a-bce1015dc4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      <webElementGuid>9afbaf88-9e6a-4231-965f-94bef4334cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon']/div</value>
      <webElementGuid>4fe6433a-8775-4b73-8a0d-9faa1b86377f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2022 CRIF High Mark Credit Information Services Pvt. Ltd.'])[1]/following::div[3]</value>
      <webElementGuid>f61da48f-5ec1-42df-8e4d-4d73d24b3c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::div[3]</value>
      <webElementGuid>f695904e-6159-4fce-abe2-8cb0340eb32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='id(&quot;login&quot;)/table[2]/tbody[1]/tr[1]/td[1]/fieldset[1]/table[1]/tbody[1]/tr[5]/td[1]/div[1]/ul[@class=&quot;errorMessage&quot;]/li[1]/span[1]']/parent::*</value>
      <webElementGuid>fd5408f2-b3b6-49c6-9bac-0b050da78afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>dcbc295f-7be5-46a9-b583-77cd37b7ffe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;login&quot;)/table[2]/tbody[1]/tr[1]/td[1]/fieldset[1]/table[1]/tbody[1]/tr[5]/td[1]/div[1]/ul[@class=&quot;errorMessage&quot;]/li[1]/span[1]' or . = 'id(&quot;login&quot;)/table[2]/tbody[1]/tr[1]/td[1]/fieldset[1]/table[1]/tbody[1]/tr[5]/td[1]/div[1]/ul[@class=&quot;errorMessage&quot;]/li[1]/span[1]')]</value>
      <webElementGuid>27d3b973-0c69-417a-b99d-6ccf79b7883d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
